# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane


platform :ios do

  desc "Beta Development Build"
  lane :beta_build do
    match(git_url: "https://github.com/nikunjagola1/certsTest.git",
          type: "development",
          username: "nikunj.agola@tatvasoft.com",
          app_identifier: "com.tatvasoft.vidoetest")
    gym(scheme: "TestGTAction", export_method: "development", clean: true)
    testflight

  end

  desc "This will also make sure the profile is up to date"
  lane :testflight_beta do
	  match(git_url: "https://github.com/nikunjagola1/Certificates.git",
		  type: "appstore",
		  app_identifier: "com.tatvasoft.vidoetest")
          gym(scheme: "TestGTAction") # Build your app - more options available
          pilot
  end


end
