# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
  	# match(type: "appstore")
    #build_app(workspace: "TestGTAction.xcworkspace", scheme: "TestGTAction")
    #upload_to_testflight
    match(git_url: "https://github.com/nikunjagola1/certsTest.git",
		  type: "appstore",
		  app_identifier: "com.tatvasoft.vidoetest")
    gym(scheme: "TestGTAction") # Build your app - more options available
    pilot
  end

  desc "Check certificates"
  lane :certificates do
    match(app_identifier: "com.tatvasoft.vidoetest")
  end

end
