# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestGTAction' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestGTAction

# RXSwift
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxGesture'

# Network
  pod 'Alamofire'
  pod 'RxAlamofire'

  pod 'AppCenter'
end
