name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=12.2,name=iPhone X']

    steps:
    - uses: actions/checkout@master
    - name: Build
      run: |
          xcodebuild -workspace TestGTAction.xcworkspace -scheme TestGTAction -destination "${destination}" build
          bash <(curl -s https://codecov.io/bash)

      env:
        destination: ${{ matrix.destination }}
