name: Fastlane

on: [push]

jobs:
  ios-testflight:
    name: iOS Testflight
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=12.2,name=iPhone X']

    steps:
    - uses: actions/checkout@master
    - name: Fastlane Build
      uses: maierj/fastlane-action@v0.10.0
      with:
        lane: 'testflight'
