name: Fastlane-7
on: push
    
jobs:
  ios-testflight:
    name: iOS Testflight
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=12.2,name=iPhone X']

    steps:
      #- name: Build and Test
      #  run: bundle exec fastlane scan --destination "${destination}" --scheme "TestGTAction"
      #  env:
      #    destination: ${{ matrix.destination }}

      - name: Checkout
        uses: actions/checkout@master
      - name: Build and test
        run: swift build -v









        #run: fastlane scan --destination "${destination}" --scheme "TestGTAction"
