name: Fastlane-6

on:
  push:
    branches:
    - master

jobs:
  ios-testflight:
    name: iOS Testflight
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=13.1,name=iPhone X']

    steps:
      #- name: Build and Test
      #  run: bundle exec fastlane scan --destination "${destination}" --scheme "TestGTAction"
      #  env:
      #    destination: ${{ matrix.destination }}

      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and test
        run: |
          cd TestGTAction
          xcodebuild clean test -project TestGTAction.xcodeproj -scheme TestGTAction -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
          bash <(curl -s https://codecov.io/bash) -t "${CODECOV_TOKEN}"
        env: 
           destination: ${{ matrix.destination }}









        #run: fastlane scan --destination "${destination}" --scheme "TestGTAction"
